// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59DDwmPt9PnquyERJkhBBaMqtCW6aHXw',
    appId: '1:1008287966035:android:73740f0b8311db6733f7a6',
    messagingSenderId: '',
    projectId: 'oder-app-tracker',
    storageBucket: 'oder-app-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAllWnMP5cV0RfOhVkNtIlhsd9XNyWq4FY',
    appId: '1:1008287966035:ios:5ad0b6c293f1da0f33f7a6',
    messagingSenderId: '',
    projectId: 'oder-app-tracker',
    storageBucket: 'oder-app-tracker.appspot.com',
    iosBundleId: 'com.example.orderTracker',
  );
}
